require('dotenv').config({ path: '.env' });
module.exports = {
  port: Number(process.env.PORT),
  twillioAccountSid: process.env.TWILIO_ACCOUNT_SID,
  twillioAuthToken: process.env.TWILIO_AUTH_TOKEN,
  authServiceSid: process.env.TWILIO_AUTHY_SERVICE_SID,
  cryptoSecret: process.env.CRYPTO_SECRET,
  jwtSecret: process.env.JWT_SECRET,
  s3Region: process.env.S3_REGION,
  s3ItemBucket: process.env.S3_ITEM_BUCKET_NAME,
  s3ItemBucketPrefix: process.env.S3_ITEM_BUCKET_PREFIX,
  maxBattleCount: process.env.MAX_BATTLES_COUNT,
  s3ItemPoolId: process.env.S3_ITEM_POOL_ID,
  contract_provider: process.env.CONTRACT_PROVIDER,
  contract_admin_pk: process.env.CONTRACT_ADMIN_PK,
  contract_address: process.env.CONTRACT_ADDRESS,
  contract_owner: process.env.CONTRACT_OWNER,
  chainId: process.env.CHAIN_ID,
  gasPrice: process.env.GAS_PRICE,
  gasLimit: process.env.GAS_LIMIT,
  // initialFuel:process.env.INITIAL_FUEL,
  db: {
    user: process.env.DB_USER || '',
    database: process.env.DB || '',
    password: process.env.DB_PASS || '',
    db_host_reader: process.env.DB_HOST_READER || '',
    db_host_writer: process.env.DB_HOST_WRITER || '',
    port: Number(process.env.DB_PORT) || 5432,
    max: Number(process.env.DB_MAX_CLIENTS) || 20,
    idleTimeoutMillis: Number(process.env.DB_IDLE_TIMEOUT_MS) || 30000
  },
  contract_min_balance: process.env.CONTRACT_MIN_BALANCE || '',
  rfm_slack_webhook: process.env.rfm_SLACK_WEBHOOK,
  season_default_lp: process.env.SEASON_LP || 0,
  season_default_league: process.env.SEASON_LEAGUE || 1,
  slack_balance_notify: process.env.SLACK_BALANCE_NOTIFY || false,
  x_api_key: process.env.X_API_KEY,
  season_treasure_box_contract: {
    provider: process.env.SEASON_TREASURE_BOX_RPC,
    chainId: process.env.SEASON_TREASURE_BOX_CHAIN_ID,
    admin_pk: process.env.SEASON_TREASURE_BOX_ADMIN_PK,
    address: process.env.SEASON_TREASURE_BOX_PROXY_ADDRESS,
    owner: process.env.SEASON_TREASURE_BOX_OWNER,
  },
  xanalia_url: process.env.NODE_ENV === 'production' ? 'https://prod-backend.xanalia.com' : 'https://backend.xanalia.com'
};
